// Vercel serverless entry — serves the Express API on the same domain as the
// static site. Every request under /api/* lands here and runs the authoritative
// server (claim, edit, delete, github sync, profanity policy).
//
// `_server-bundle.mjs` is generated by `scripts/build-api.mjs` (inlines
// workspace packages, keeps npm packages external). Regenerate it after any
// change to apps/server/src.
import { app } from './_server-bundle.mjs';
import type { IncomingMessage, ServerResponse } from 'node:http';

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  if (!req.url || !req.url.startsWith('/api')) {
    req.url = `/api${req.url || ''}`;
  }
  return app(req as any, res as any);
}
